# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.



# Do not keep production secrets in the repository,
# instead read values from the environment.

development:
  secret_key_base: aa2267f40ebcad39d8c1b80131490e2cd69abc441948bf9a9eee393601c86cc15ab1dddbcab17b40255f56beb745572319188ae1a672b62d00c8ae4d3177af16
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 5410dc1eb4b403b9e6bc02efbca2c0ad75ed6527226eed98ced0b93cbc5e0ad19b41e9ddc4220b6226b1580d5399983aa4a08832c253f0cf2cc5ce25db73ae7e

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>